---
include:
  - board: adv360_left
    artifact-name: firmware-left
  - board: adv360_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: firmware-left-clique
  - board: adv360_right
    artifact-name: firmware-right
