name: Lint
on: [push, pull_request]

jobs:
  dts-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g --ignore-scripts dts-linter
      - name: Check DTS formatting
        run: >-
          dts-linter --format --diagnostics
          --file config/adv360.keymap
          --file config/macros.dtsi
          --file boards/arm/adv360/*.dts
          --file boards/arm/adv360/*.dtsi
